FROM python:3.11-slim

# Disable .pyc files + enable unbuffered logs
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install deps
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy code
COPY . /app/

# Expose Django dev port
EXPOSE 8000

# Run Django dev server (SQLite by default)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
